### ISSUE TITLE
In centimeters... min/max privacy issue?

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/proximity#10]
I wonder if min and max will become a way of fingerprinting or identifying users of particular proximity sensors. Like Company X Sensors all have a max of 10.3232 cm. 

Maybe there needs to be a Privacy recommendation that user agents round or pad min and max to avoid such things?

**Comment by marcoscaceres** [comment]
Might be duplicate of https://github.com/w3c/proximity/issues/3

**Comment by lknik** [comment]
I am composing privacy recommendations and I'll send them soon. I don't think any platform should report so verbose readouts, though.

**Comment by anssiko** [comment]
Feedback integrated into #17.
