### ISSUE TITLE
What's the initial value of near attribute?

### ISSUE THREAD

**Issue by xiuqijix** [w3c/proximity#29]
Generic Sensor [spec](https://w3c.github.io/sensors/#model-sensor) states that:  
>The value of all latest reading entries is initially set to null.

But near attribute is boolean in [Proximity](https://w3c.github.io/proximity/#proximity-sensor-near) which could not be set to null.

**Comment by Honry** [comment]
In [previous version](https://www.w3.org/TR/2015/WD-proximity-20150903/#widl-UserProximityEventInit-near), the near attribute is initialized to false.

> The near attribute of the UserProximityEvent interface must return the value it was initialized to. When the object is created, this attribute must be initialized to false.

**Comment by riju** [comment]
> But near attribute is boolean in Proximity which could not be set to null.

Can you please get me the link, where I can check boolean cannot be null ?

We did consider it to be initialized to 'false', 
There might be some confusion as to what  near == false means 
1. platform cannot give near value
2. imply there is NOT an object in the sensing range

Hence the Note : 

> If the implementation is unable to provide the near value, it could infer the near value from the value of distance. For example, if distance is not equal to max, it could imply there is an object in the sensing range.

**Comment by anssiko** [comment]
The [`near` attribute](https://w3c.github.io/proximity/#dom-proximitysensor-near) is a [nullable type](https://heycam.github.io/webidl/#es-nullable-type) and can be null.

To be consistent with the other Generic Sensor-based APIs, I think also this spec should default to null (and not to false as in the previous version that was not based on the Generic Sensor API).

**Comment by xiuqijix** [comment]
Sorry, I am not quite familiar with Web IDL, thanks for your clarification, close it.

**Comment by anssiko** [comment]
No problem. Thanks for reviewing the spec. Please let us know if you identify other issues.
