### ISSUE TITLE
Update spec to new IDL syntax for optional dictionaries

### ISSUE THREAD

**Issue by Ms2ger** [w3c/proximity#40]
See heycam/webidl#758

**Comment by anssiko** [comment]
A fix landed in https://github.com/w3c/proximity/pull/39

From the context I infer you refer to the legacy `DeviceProximityEvent` (originating from Firefox OS) and not to `ProximitySensor` this spec is about. The legacy event is implemented in Gecko only AFAICT and for that there's no spec that is maintained.
