### ISSUE TITLE
https://w3c.github.io/proximity/ not updated

### ISSUE THREAD

**Issue by foolip** [w3c/proximity#45]
https://github.com/w3c/proximity/commit/9fa57e3053e89d0c9c519ec046d2bdd646308d4f never deployed, so https://w3c.github.io/proximity/ does not reflect the most recent changes to the spec. @anssiko would you be able to retry the job or otherwise get the published spec in sync again?

**Comment by anssiko** [comment]
@foolip, thanks for reporting this deploy bug. This is now fixed, in particular e1c17823ffb634509a91068a8a271b17be5e0c0d that was not initially deployed now is.

**Comment by foolip** [comment]
Thanks @anssiko!
