### ISSUE TITLE
Model section duplicates IDL

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/proximity#5]
There appears to be prose that replicates what is already in the WebIDL. I would encourage you not to do this - it's easier to just look at the IDL to get a sense of what extends what, etc. 

In other words, if it's in the IDL, it should not be in the prose.

**Comment by anssiko** [comment]
IDL is not expressive enough in this case, thus each concrete sensor spec includes such a Model section that fills it in, and links to the concepts defined in the Generic Sensor API. For the abstract Model, see: https://w3c.github.io/sensors/#model
