### ISSUE TITLE
Maybe add a "limitations of proximity sensors" section

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/proximity#6]
In the intro, the text that starts with:

>  "Since most proximity sensors detect electromagnetic radiation (e.g., an infrared light or a magnetic field), certain material properties can interfere with the sensor’s ability to sense the presence of a physical object. "

Should probably be in its own section, maybe at the end of the document. Although it's good text (heh, I'm biased), it doesn't add much to the introduction. Maybe the intro can just link to the limitations.

**Comment by anssiko** [comment]
Agreed, we'll fix this. Thanks! I guess this text originated from you :-)
